#!/bin/bash
MSGS=/tmp/msgs
DZEN_GEOMETRY='-w 1280 -h 25'
DZEN_FONT='dejavu sans condensed'

while read INP; do
  REP="[$(date +%H:%M:%S)]   ${INP}"
  echo -e "${REP}" >> "${MSGS}"
  if [ -n "$DISPLAY" ]; then
    echo -e "${REP}" | dzen2 -fn \'"${DZEN_FONT}"\' -p 3 ${DZEN_GEOMETRY}
  fi
done

